### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by ghost** [MrAli-Code/MadelineProto#1]

**Comment by MrAli-Code** [comment]
> یه کم فقط یه کم بقیه رپوزیتوری های گیتهابو نگاه کن ببین چجوری بر پایه مثلا مدلاین یه پروژه میزنن آبرومونو امثال شما میبرن تو دنیا

تازه رسیدی اجازه بده عرق تنت خشک بشه بعد .
جوون هستی و جویای نام
